# Diamond pickaxe option:
# If enabled true, it will be able to mine spawners with or without enchantmentes, just any diamond pickaxe:
# If silk_touch_required true, you'll mine only if your diamond pick have enchanted with silk_touch
Diamond_Pickaxe:
  Enabled: true
  Silk_Touch_Required: true

# This options are independent you may select true only iron pickaxe if you want it
# Iron pickaxe option, if enabled true, it will be able to mine spawners with or without enchantmentes, just any iron pickaxe
# If silk_touch_required true, you'll mine only if your iron pick have enchanted with silk_touch
# If enabled option is set to false, silk_touch_required will be irrelevant
Iron_Pickaxe:
  Enabled: false
  Silk_Touch_Required: false

# The option to allow mob spawners change:
# By right clicking spawner it with a spawn egg in main hand to change it is native, using this option you can turn it off, if wanted
Allow_SpawnEgg_Change:
  Enabled: true
  
# Prevent spawner change while player is invisible by SuperVanish plugin
SuperVanish_Prevent_SpawnEgg_Change:
  Enabled: true